### ISSUE TITLE
An unexpected exception raises by the implementation of the user register function using dj_rest_auth.registration

### ISSUE THREAD

**Issue by hajime-f** [jazzband/dj-rest-auth#203]
Using dj_rest_auth 2.1.2, I could implement JWT authentication functions. Thank you to all the developers.
Here, I'd like to report an unexpected exception I've encountered.

After the implementation above, I tried to implement a registration function using dj_rest_auth.registration.

```python:settings.py
INSTALLED_APPS = [
    ...
    'django.contrib.sites',

    'rest_framework',
    'rest_framework.authtoken',
    'allauth',
    'allauth.account',
    'allauth.socialaccount',
    'dj_rest_auth',
    'dj_rest_auth.registration',   ## add
    ...
]

SITE_ID = 1
REST_USE_JWT = True
JWT_AUTH_COOKIE = 'user'
AUTH_USER_MODEL = 'users.User'

SIMPLE_JWT = {
    'USER_ID_FIELD': 'uuid',
}

ACCOUNT_AUTHENTICATION_METHOD = 'email'
ACCOUNT_USERNAME_REQUIRED = False
ACCOUNT_USER_MODEL_USERNAME_FIELD = None
```

```python:urls.py
urlpatterns = [
    path('admin/', admin.site.urls),
    path('dj-rest-auth/', include('dj_rest_auth.urls')),
    path('dj-rest-auth/registration/', include('dj_rest_auth.registration.urls')),  ## add
]
```

It worked well at the endpoint ```/dj-rest-auth/registration/```. 

The other hand, however, the JWT authentication functions of dj_rest_auth that worked well before has no longer worked well by the exception ```EmailAddress matching query does not exist``` (of cause, the email address was registered via the admin backend).

I could access the endpoint, for example ```/dj-rest-auth/login/``` using the browser. But, the exception appears when I POST the registered email and password.
 
I guess that the exception may be due to the custom user model that is inherited AbstractBaseUser; I implemented the model that enables users authenticated only using email (no username is required). 

I hope the information gives the developers a hint and appreciate it if you give me some advice to solve this problem.
Thank you.

**Comment by mohmyo** [comment]
Can you share your error trace log?

**Comment by hajime-f** [comment]
Sorry, I forgot that. The error log is below:

```
Environment:
Request Method: POST
Request URL: http://127.0.0.1:8081/dj-rest-auth/login/

Django Version: 3.1.4
Python Version: 3.9.1
Installed Applications:
['django.contrib.admin',
 'django.contrib.auth',
 'django.contrib.contenttypes',
 'django.contrib.sessions',
 'django.contrib.messages',
 'django.contrib.staticfiles',
 'django.contrib.sites',
 'rest_framework',
 'rest_framework.authtoken',
 'allauth',
 'allauth.account',
 'allauth.socialaccount',
 'dj_rest_auth',
 'dj_rest_auth.registration',
 'users',
 'orchestra']
Installed Middleware:
['django.middleware.security.SecurityMiddleware',
 'django.contrib.sessions.middleware.SessionMiddleware',
 'django.middleware.common.CommonMiddleware',
 'django.middleware.csrf.CsrfViewMiddleware',
 'django.contrib.auth.middleware.AuthenticationMiddleware',
 'django.contrib.messages.middleware.MessageMiddleware',
 'django.middleware.clickjacking.XFrameOptionsMiddleware']

Traceback (most recent call last):
  File "/usr/local/lib/python3.9/site-packages/django/core/handlers/exception.py", line 47, in inner
    response = get_response(request)
  File "/usr/local/lib/python3.9/site-packages/django/core/handlers/base.py", line 179, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/usr/local/lib/python3.9/site-packages/django/views/decorators/csrf.py", line 54, in wrapped_view
    return view_func(*args, **kwargs)
  File "/usr/local/lib/python3.9/site-packages/django/views/generic/base.py", line 70, in view
    return self.dispatch(request, *args, **kwargs)
  File "/usr/local/lib/python3.9/site-packages/django/utils/decorators.py", line 43, in _wrapper
    return bound_method(*args, **kwargs)
  File "/usr/local/lib/python3.9/site-packages/django/views/decorators/debug.py", line 89, in sensitive_post_parameters_wrapper
    return view(request, *args, **kwargs)
  File "/usr/local/lib/python3.9/site-packages/dj_rest_auth/views.py", line 48, in dispatch
    return super(LoginView, self).dispatch(*args, **kwargs)
  File "/usr/local/lib/python3.9/site-packages/rest_framework/views.py", line 509, in dispatch
    response = self.handle_exception(exc)
  File "/usr/local/lib/python3.9/site-packages/rest_framework/views.py", line 469, in handle_exception
    self.raise_uncaught_exception(exc)
  File "/usr/local/lib/python3.9/site-packages/rest_framework/views.py", line 480, in raise_uncaught_exception
    raise exc
  File "/usr/local/lib/python3.9/site-packages/rest_framework/views.py", line 506, in dispatch
    response = handler(request, *args, **kwargs)
  File "/usr/local/lib/python3.9/site-packages/dj_rest_auth/views.py", line 138, in post
    self.serializer.is_valid(raise_exception=True)
  File "/usr/local/lib/python3.9/site-packages/rest_framework/serializers.py", line 220, in is_valid
    self._validated_data = self.run_validation(self.initial_data)
  File "/usr/local/lib/python3.9/site-packages/rest_framework/serializers.py", line 422, in run_validation
    value = self.validate(value)
  File "/usr/local/lib/python3.9/site-packages/dj_rest_auth/serializers.py", line 131, in validate
    self.validate_email_verification_status(user)
  File "/usr/local/lib/python3.9/site-packages/dj_rest_auth/serializers.py", line 112, in validate_email_verification_status
    email_address = user.emailaddress_set.get(email=user.email)
  File "/usr/local/lib/python3.9/site-packages/django/db/models/manager.py", line 85, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
  File "/usr/local/lib/python3.9/site-packages/django/db/models/query.py", line 429, in get
    raise self.model.DoesNotExist(

Exception Type: DoesNotExist at /dj-rest-auth/login/
Exception Value: EmailAddress matching query does not exist.
```

**Comment by mohmyo** [comment]
As error trace shows, the the error was triggered by [validate_email_verification_status()](https://github.com/jazzband/dj-rest-auth/blob/cb8e5388a7877a7e41861d0523291b07b3b6ca35/dj_rest_auth/serializers.py#L109).

When looking at the implementation I can see that the error happened because `if app_settings.EMAIL_VERIFICATION == app_settings.EmailVerificationMethod.MANDATORY:` was true and therefore `email_address = user.emailaddress_set.get(email=user.email)` will be executed. If there was no record for that email it will throw that error because `get()` expects that the record exists.

Take a look on your `ACCOUNT_EMAIL_VERIFICATION` value att `settings.py` and make sure that if it was set to `MANDATORY` then the user's email address exists at `EmailAddresses`.

**Comment by hajime-f** [comment]
Thanks to your kind advice, I was able to solve the problem.
I'd like to share what I have tried.

As mohmyo said, I define ```ACCOUNT_EMAIL_VERIFICATION = 'mandatory'``` in ```settings.py``` to block from logging in until the email address verified. 

```python
ACCOUNT_EMAIL_REQUIRED = True
ACCOUNT_UNIQUE_EMAIL = True
ACCOUNT_EMAIL_VERIFICATION = 'mandatory'  # <- this
ACCOUNT_CONFIRM_EMAIL_ON_GET = True
LOGIN_REDIRECT_URL = '/'
ACCOUNT_LOGOUT_REDIRECT_URL = '/'
```

When I confirm the ```User``` table on the database, the record that includes the email of the test user exists. 
I simply assumed, therefore, that the test user should be able to login.

```
mysql> select email, username from User;
+-------------------------+----------+
| email                   | username |
+-------------------------+----------+
| hajime-f@test.com       | NULL     |  # <-- This is the superuser.
| test@test.com           | test     |  # <-- This is the test user that I try to login
+-------------------------+----------+
2 rows in set (0.00 sec)
```

But, I noticed that the ```account_emailaddress``` table was empty. 

```
mysql> select * from account_emailaddress;
Empty set (0.00 sec)
```

So, I registered the email via the admin backend.

```
mysql> select * from account_emailaddress;
+----+---------------+----------+---------+----------------------------------+
| id | email         | verified | primary | user_id                          |
+----+---------------+----------+---------+----------------------------------+
|  3 | test@test.com |        1 |       0 | 5d1aa3dfaf7c40009fa8631737d3d720 |
+----+---------------+----------+---------+----------------------------------+
```

I could log in at the endpoint ```/dj-rest-auth/login/```.
Very nice!

I understand that, when ```ACCOUNT_EMAIL_VERIFICATION``` is set to ```mandatory```, the user may be registered, but not the email address at the same time even using the admin backend. Therefore, we have to register both of the user and its email with the verification.

I also understand that, on the production stage, when an user registers its email, it will be temporarily registered to ```User``` table, before when the user completes the confirmation, it will be registered to ```account_emailaddress``` then the user will be able to login.

Thank you.

**Comment by mohmyo** [comment]
Great explanation and nice work! @hajime-f
