### ISSUE TITLE
Error on demo:  'str' object has no attribute 'decode'

### ISSUE THREAD

**Issue by YiannisGkoufas** [jazzband/dj-rest-auth#211]
Hi there,

I was trying the demo project ( https://dj-rest-auth.readthedocs.io/en/latest/demo.html ) and when I tried to login I got the error:

```
Internal Server Error: /dj-rest-auth/login/
Traceback (most recent call last):
  File "/home/yiannis/.local/share/virtualenvs/demo-wgKabU28/lib/python3.7/site-packages/django/core/handlers/exception.py", line 47, in inner
    response = get_response(request)
  File "/home/yiannis/.local/share/virtualenvs/demo-wgKabU28/lib/python3.7/site-packages/django/core/handlers/base.py", line 181, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/yiannis/.local/share/virtualenvs/demo-wgKabU28/lib/python3.7/site-packages/django/views/decorators/csrf.py", line 54, in wrapped_view
    return view_func(*args, **kwargs)
  File "/home/yiannis/.local/share/virtualenvs/demo-wgKabU28/lib/python3.7/site-packages/django/views/generic/base.py", line 70, in view
    return self.dispatch(request, *args, **kwargs)
  File "/home/yiannis/.local/share/virtualenvs/demo-wgKabU28/lib/python3.7/site-packages/django/utils/decorators.py", line 43, in _wrapper
    return bound_method(*args, **kwargs)
  File "/home/yiannis/.local/share/virtualenvs/demo-wgKabU28/lib/python3.7/site-packages/django/views/decorators/debug.py", line 89, in sensitive_post_parameters_wrapper
    return view(request, *args, **kwargs)
  File "/home/yiannis/.local/share/virtualenvs/demo-wgKabU28/lib/python3.7/site-packages/dj_rest_auth/views.py", line 48, in dispatch
    return super(LoginView, self).dispatch(*args, **kwargs)
  File "/home/yiannis/.local/share/virtualenvs/demo-wgKabU28/lib/python3.7/site-packages/rest_framework/views.py", line 509, in dispatch
    response = self.handle_exception(exc)
  File "/home/yiannis/.local/share/virtualenvs/demo-wgKabU28/lib/python3.7/site-packages/rest_framework/views.py", line 469, in handle_exception
    self.raise_uncaught_exception(exc)
  File "/home/yiannis/.local/share/virtualenvs/demo-wgKabU28/lib/python3.7/site-packages/rest_framework/views.py", line 480, in raise_uncaught_exception
    raise exc
  File "/home/yiannis/.local/share/virtualenvs/demo-wgKabU28/lib/python3.7/site-packages/rest_framework/views.py", line 506, in dispatch
    response = handler(request, *args, **kwargs)
  File "/home/yiannis/.local/share/virtualenvs/demo-wgKabU28/lib/python3.7/site-packages/dj_rest_auth/views.py", line 141, in post
    return self.get_response()
  File "/home/yiannis/.local/share/virtualenvs/demo-wgKabU28/lib/python3.7/site-packages/dj_rest_auth/views.py", line 104, in get_response
    response = Response(serializer.data, status=status.HTTP_200_OK)
  File "/home/yiannis/.local/share/virtualenvs/demo-wgKabU28/lib/python3.7/site-packages/rest_framework/serializers.py", line 548, in data
    ret = super().data
  File "/home/yiannis/.local/share/virtualenvs/demo-wgKabU28/lib/python3.7/site-packages/rest_framework/serializers.py", line 246, in data
    self._data = self.to_representation(self.instance)
  File "/home/yiannis/.local/share/virtualenvs/demo-wgKabU28/lib/python3.7/site-packages/rest_framework/serializers.py", line 515, in to_representation
    ret[field.field_name] = field.to_representation(attribute)
  File "/home/yiannis/.local/share/virtualenvs/demo-wgKabU28/lib/python3.7/site-packages/rest_framework/fields.py", line 811, in to_representation
    return str(value)
  File "/home/yiannis/.local/share/virtualenvs/demo-wgKabU28/lib/python3.7/site-packages/rest_framework_simplejwt/tokens.py", line 82, in __str__
    return token_backend.encode(self.payload)
  File "/home/yiannis/.local/share/virtualenvs/demo-wgKabU28/lib/python3.7/site-packages/rest_framework_simplejwt/backends.py", line 43, in encode
    return token.decode('utf-8')
AttributeError: 'str' object has no attribute 'decode'
[17/Jan/2021 17:15:10] "POST /dj-rest-auth/login/ HTTP/1.1" 500 31341
```
Any help is appreciated!

**Comment by mohmyo** [comment]
This happed due to the recent update for `PyJWT` to version` 2.0.0`, installing `PyJWT` 1.7.0` instead should fix this problem.

**Comment by jchinte** [comment]
I changed the requirement for SimpleJWT from 4.4.0 to 4.6.0 and the update fixed the problem.

**Comment by Frank5000** [comment]
> This happened due to the recent update of `PyJWT` to version` 2.0.0`, installing `PyJWT 1.7.0` instead should fix this problem.

Worked for me
