### ISSUE TITLE
Login / registration problems with React

### ISSUE THREAD

**Issue by saiikuron** [jazzband/dj-rest-auth#90]
I get this error for the backend: 

> Exception happened during processing of request from ('127.0.0.1', 60701)
Traceback (most recent call last):
  File "d:\library\logiciels\python\Lib\socketserver.py", line 650, in process_request_thread     
    self.finish_request(request, client_address)
  File "d:\library\logiciels\python\Lib\socketserver.py", line 360, in finish_request
    self.RequestHandlerClass(request, client_address, self)
  File "d:\library\logiciels\python\Lib\socketserver.py", line 720, in __init__
    self.handle()
  File "C:\Users\Sébastien\.virtualenvs\backend-jtfyeVPq\lib\site-packages\django\core\servers\basehttp.py", line 171, in handle
    self.handle_one_request()
  File "C:\Users\Sébastien\.virtualenvs\backend-jtfyeVPq\lib\site-packages\django\core\servers\basehttp.py", line 179, in handle_one_request
    self.raw_requestline = self.rfile.readline(65537)
  File "d:\library\logiciels\python\Lib\socket.py", line 669, in readinto
    return self._sock.recv_into(b)
ConnectionAbortedError: [WinError 10053] An established connection was aborted by the software in your host machine

Here is the Login.jsx code:
```
import React, { useState, setTimeout } from "react";
import axios from "axios";
import Form from "react-bootstrap/Form";
import Button from "react-bootstrap/Button";

export function Login() {
  const [username, setUsername] = useState();
  const [email, setEmail] = useState();
  const [password, setPassword] = useState();

  const loginUser = () => {
    const data = {
      username,
      email,
      password,
    };
    axios
      .post("http://localhost:8000/auth/login/", data)
      .then((res) => {
        console.log(res);
      })
      .catch((err) => {
        console.log(err);
      });
  };
  return (
    <div className="container">
      <Form onSubmit={loginUser}>
        <Form.Group controlId="formRegisterUser">
          <Form.Label>Username</Form.Label>
          <Form.Control
            placeholder="Enter your username"
            onChange={(evt) => setUsername(evt.target.value)}
          />
          <br />
          <Form.Label>Email</Form.Label>
          <Form.Control
            placeholder="Enter your email adress"
            type="email"
            onChange={(evt) => setEmail(evt.target.value)}
          />
          <br />
          <Form.Label>Password</Form.Label>
          <Form.Control
            placeholder="Enter your password"
            onChange={(evt) => setPassword(evt.target.value)}
          />
        </Form.Group>
        <Button className="float-right" variant="primary" type="submit">
          Login
        </Button>
      </Form>
    </div>
  );
}
```
I don't have any issues by doing it in DRF or Postman.
Here is the repo if you need it: [https://github.com/saiikuron/DRF-React](url)

**Comment by saiikuron** [comment]
my bad, I forgot e.preventDefault();
